name: Terraform CI
on:
  push:
    paths-ignore:
      - '**/README.md'
    branches:
      - master

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform SetUp
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.4
          terraform_wrapper: false
  
      - name: Formating terraform code
        run: terraform fmt -recursive

      - name: Configure Terraform Cloud Token
        run: echo '{"credentials":{"app.terraform.io":{"token":"'${{ secrets.TF_API_TOKEN }}'"}}}' > $HOME/.terraform.d/credentials.tfrc.json

      - name: Initializing Backend
        run: terraform init -reconfigure

      - name: Terraform Plan
        run: terraform plan

      # - name: DEPLOYING THE INFRASTRUCTURE
      #   run: terraform apply -auto-approve
